# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++MPE+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# -------------------------------------------------------------TAG-------------------------------------------------------------
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="0" nohup python3 -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="none" exp_name="TAG-QMIX-B" test_nepisode=1 evaluate=True checkpoint_path="./results/models/pz-mpe-simple-tag-v3/pd_qmix/TAG-QMIX-B_2026-02-12 23:50:33.406275_pd_qmix_seed707788613"' 'tag_test_qmix_b.log'
# sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="0" nohup python3 -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="none" exp_name="TAG-QMIX-N" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_qmix_n.log'
# sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="0" nohup python3 -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="none" exp_name="TAG-QMIX-DA" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_qmix_da.log'

# -------------------------------------------------------------SPREAD-------------------------------------------------------------
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="0" nohup python3 -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="none" exp_name="SPREAD-QMIX-B" test_nepisode=1 evaluate=True checkpoint_path="./results/models/pz-mpe-simple-spread-v3/pd_qmix/SPREAD-QMIX-B_2026-02-14 10:16:02.677269_pd_qmix_seed419326129"' 'spread_test_qmix_b.log'
# sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="0" nohup python3 -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="none" exp_name="SPREAD-QMIX-N" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_qmix_n.log'
# sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="0" nohup python3 -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="none" exp_name="SPREAD-QMIX-DA" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_qmix_da.log'
