import re

# The raw block of commands you provided
raw_commands = """
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++MPE+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# -------------------------------------------------------------TAG-------------------------------------------------------------
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="none" delay_aware=True cheating_start_value=1.0 cheating_end_value=1.0 exp_name="TAG-QMIX-B" >> tag_qmix_b.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="none" exp_name="TAG-QMIX-N" >> tag_qmix_n.log 2>&1 &
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="none" delay_aware=True exp_name="TAG-QMIX-DA" >> tag_qmix_da.log 2>&1 &

#####transformer#####
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True exp_name="TAG-QMIX-TRANS-MS" >> tag_qmix_trans_ms.log 2>&1
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True exp_name="TAG-QMIX-TRANS-SS" >> tag_qmix_trans_ss.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True  use_history=True exp_name="TAG-QMIX-TRANS-MS-H" >> tag_qmix_trans_ms_h.log 2>&1 &
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True  use_history=True exp_name="TAG-QMIX-TRANS-SS-H" >> tag_qmix_trans_ss_h.log 2>&1 &
# curriculum learning
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True  cheating_start_value=1.0 exp_name="TAG-QMIX-TRANS-MS-H-C" >> tag_qmix_trans_ms_h_c.log 2>&1
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True  cheating_start_value=1.0 exp_name="TAG-QMIX-TRANS-SS-H-C" >> tag_qmix_trans_ss_h_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True  teacher_forcing_start_value=1.0 exp_name="TAG-QMIX-TRANS-MS-H-TF" >> tag_qmix_trans_ms_h_tf.log 2>&1 &
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True  teacher_forcing_start_value=1.0 exp_name="TAG-QMIX-TRANS-SS-H-TF" >> tag_qmix_trans_ss_h_tf.log 2>&1 &
# teacher-student
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=5050000 exp_name="TAG-QMIX-TRANS-SS-TEACHER" >> tag_qmix_trans_ss_teacher.log 2>&1
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True  teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="TAG-QMIX-TRANS-SS-STUDENT" >> tag_qmix_trans_ss_student.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=5050000 exp_name="TAG-QMIX-TRANS-SS-H-TEACHER" >> tag_qmix_trans_ss_h_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True  use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="TAG-QMIX-TRANS-SS-H-STUDENT" >> tag_qmix_trans_ss_h_student.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=5050000 exp_name="TAG-QMIX-TRANS-MS-H-TEACHER" >> tag_qmix_trans_ms_h_teacher.log 2>&1 
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True  use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="TAG-QMIX-TRANS-MS-H-STUDENT" >> tag_qmix_trans_ms_h_student.log 2>&1 &


#####gru#####
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="multi_step" delay_aware=True  exp_name="TAG-QMIX-GRU-MS" >> tag_qmix_gru_ms.log 2>&1 &
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" delay_aware=True  exp_name="TAG-QMIX-GRU-SS" >> tag_qmix_gru_ss.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="multi_step" delay_aware=True  use_history=True exp_name="TAG-QMIX-GRU-MS-H" >> tag_qmix_gru_ms_h.log 2>&1
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" delay_aware=True  use_history=True exp_name="TAG-QMIX-GRU-SS-H" >> tag_qmix_gru_ss_h.log 2>&1 &
# curriculum learning
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="multi_step" delay_aware=True use_history=True  cheating_start_value=1.0 exp_name="TAG-QMIX-GRU-MS-H-C" >> tag_qmix_gru_ms_h_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" delay_aware=True use_history=True  cheating_start_value=1.0 exp_name="TAG-QMIX-GRU-SS-H-C" >> tag_qmix_gru_ss_h_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="multi_step" delay_aware=True use_history=True  teacher_forcing_start_value=1.0 exp_name="TAG-QMIX-GRU-MS-H-TF" >> tag_qmix_gru_ms_h_tf.log 2>&1
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" delay_aware=True use_history=True  teacher_forcing_start_value=1.0 exp_name="TAG-QMIX-GRU-SS-H-TF" >> tag_qmix_gru_ss_h_tf.log 2>&1 &
# teacher-student
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" delay_aware=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=5050000 exp_name="TAG-QMIX-GRU-SS-TEACHER" >> tag_qmix_gru_ss_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" delay_aware=True   teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="TAG-QMIX-GRU-SS-STUDENT" >> tag_qmix_gru_ss_student.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" delay_aware=Trueuse_history=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=5050000 exp_name="TAG-QMIX-GRU-SS-H-TEACHER" >> tag_qmix_gru_ss_h_teacher.log 2>&1
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" delay_aware=True   use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="TAG-QMIX-GRU-SS-H-STUDENT" >> tag_qmix_gru_ss_h_student.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="multi_step" delay_aware=Trueuse_history=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=5050000 exp_name="TAG-QMIX-GRU-MS-H-TEACHER" >> tag_qmix_gru_ms_h_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="multi_step" delay_aware=True   use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="TAG-QMIX-GRU-MS-H-STUDENT" >> tag_qmix_gru_ms_h_student.log 2>&1 &


# -------------------------------------------------------------SPREAD-------------------------------------------------------------
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="none" delay_aware=True   cheating_start_value=1.0 cheating_end_value=1.0 exp_name="SPREAD-QMIX-B" >> spread_qmix_b.log 2>&1
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="none" exp_name="SPREAD-QMIX-N" >> spread_qmix_n.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="none" delay_aware=True   exp_name="SPREAD-QMIX-DA" >> spread_qmix_da.log 2>&1 &

#####transformer#####
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True   exp_name="SPREAD-QMIX-TRANS-MS" >> spread_qmix_trans_ms.log 2>&1 &
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True   exp_name="SPREAD-QMIX-TRANS-SS" >> spread_qmix_trans_ss.log 2>&1
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True   use_history=True exp_name="SPREAD-QMIX-TRANS-MS-H" >> spread_qmix_trans_ms_h.log 2>&1 &
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True   use_history=True exp_name="SPREAD-QMIX-TRANS-SS-H" >> spread_qmix_trans_ss_h.log 2>&1 &
# curriculum learning
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True   use_history=True cheating_start_value=1.0 exp_name="SPREAD-QMIX-TRANS-MS-H-C" >> spread_qmix_trans_ms_h_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-conf ig=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True   use_history=True cheating_start_value=1.0 exp_name="SPREAD-QMIX-TRANS-SS-H-C" >> spread_qmix_trans_ss_h_c.log 2>&1
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True   use_history=True teacher_forcing_start_value=1.0 exp_name="SPREAD-QMIX-TRANS-MS-H-TF" >> spread_qmix_trans_ms_h_tf.log 2>&1 &
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True   use_history=True teacher_forcing_start_value=1.0 exp_name="SPREAD-QMIX-TRANS-SS-H-TF" >> spread_qmix_trans_ss_h_tf.log 2>&1 &
# teacher-student
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=5050000 exp_name="SPREAD-QMIX-TRANS-SS-TEACHER" >> spread_qmix_trans_ss_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True  teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="SPREAD-QMIX-TRANS-SS-STUDENT" >> spread_qmix_trans_ss_student.log 2>&1
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=5050000 exp_name="SPREAD-QMIX-TRANS-SS-H-TEACHER" >> spread_qmix_trans_ss_h_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True  use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="SPREAD-QMIX-TRANS-SS-H-STUDENT" >> spread_qmix_trans_ss_h_student.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=5050000 exp_name="SPREAD-QMIX-TRANS-MS-H-TEACHER" >> spread_qmix_trans_ms_h_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True  use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="SPREAD-QMIX-TRANS-MS-H-STUDENT" >> spread_qmix_trans_ms_h_student.log 2>&1

#####gru#####
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="multi_step" delay_aware=True  exp_name="SPREAD-QMIX-GRU-MS" >> spread_qmix_gru_ms.log 2>&1 &
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" delay_aware=True  exp_name="SPREAD-QMIX-GRU-SS" >> spread_qmix_gru_ss.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="multi_step" delay_aware=True  use_history=True exp_name="SPREAD-QMIX-GRU-MS-H" >> spread_qmix_gru_ms_h.log 2>&1 &
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" delay_aware=True  use_history=True exp_name="SPREAD-QMIX-GRU-SS-H" >> spread_qmix_gru_ss_h.log 2>&1
# curriculum learning
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="multi_step" delay_aware=True  use_history=True cheating_start_value=1.0 exp_name="SPREAD-QMIX-GRU-MS-H-C" >> spread_qmix_gru_ms_h_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" delay_aware=True  use_history=True cheating_start_value=1.0 exp_name="SPREAD-QMIX-GRU-SS-H-C" >> spread_qmix_gru_ss_h_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="multi_step" delay_aware=True  use_history=True teacher_forcing_start_value=1.0 exp_name="SPREAD-QMIX-GRU-MS-H-TF" >> spread_qmix_gru_ms_h_tf.log 2>&1 &
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" delay_aware=True  use_history=True teacher_forcing_start_value=1.0 exp_name="SPREAD-QMIX-GRU-SS-H-TF" >> spread_qmix_gru_ss_h_tf.log 2>&1 
# teacher-student
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" delay_aware=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=5050000 exp_name="SPREAD-QMIX-GRU-SS-TEACHER" >> spread_qmix_gru_ss_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" delay_aware=True  teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="SPREAD-QMIX-GRU-SS-STUDENT" >> spread_qmix_gru_ss_student.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=5050000 exp_name="SPREAD-QMIX-GRU-SS-H-TEACHER" >> spread_qmix_gru_ss_h_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" delay_aware=True  use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="SPREAD-QMIX-GRU-SS-H-STUDENT" >> spread_qmix_gru_ss_h_student.log 2>&1
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="multi_step" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=5050000 exp_name="SPREAD-QMIX-GRU-MS-H-TEACHER" >> spread_qmix_gru_ms_h_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="multi_step" delay_aware=True  use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="SPREAD-QMIX-GRU-MS-H-STUDENT" >> spread_qmix_gru_ms_h_student.log 2>&1


# # -------------------------------------------------------------REFERENCE-------------------------------------------------------------
# CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="none" delay_aware=True cheating_start_value=1.0 cheating_end_value=1.0 t_max=100000 exp_name="REFERENCE-QMIX-B" >> reference_qmix_b.log 2>&1
# CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="none" t_max=100000 exp_name="REFERENCE-QMIX-N" >> reference_qmix_n.log 2>&1
# CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="none" delay_aware=True t_max=100000 exp_name="REFERENCE-QMIX-DA" >> reference_qmix_da.log 2>&1

# #####transformer#####
# CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True t_max=100000 exp_name="REFERENCE-QMIX-TRANS-MS" >> reference_qmix_trans_ms.log 2>&1
# CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True t_max=100000 exp_name="REFERENCE-QMIX-TRANS-SS" >> reference_qmix_trans_ss.log 2>&1
# CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True t_max=100000 exp_name="REFERENCE-QMIX-TRANS-MS-H" >> reference_qmix_trans_ms_h.log 2>&1
# CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True t_max=100000 exp_name="REFERENCE-QMIX-TRANS-SS-H" >> reference_qmix_trans_ss_h.log 2>&1
# # curriculum learning
# CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True cheating_start_value=1.0 cheating_start_time=2000000 cheating_end_time=6000000 t_max=100000 exp_name="REFERENCE-QMIX-TRANS-MS-H-C" >> reference_qmix_trans_ms_h_c.log 2>&1
# CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True cheating_start_value=1.0 cheating_start_time=2000000 cheating_end_time=6000000 t_max=100000 exp_name="REFERENCE-QMIX-TRANS-SS-H-C" >> reference_qmix_trans_ss_h_c.log 2>&1
# CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True teacher_forcing_start_value=1.0 teacher_forcing_start_time=2000000 teacher_forcing_end_time=6000000 t_max=100000 exp_name="REFERENCE-QMIX-TRANS-MS-H-TF" >> reference_qmix_trans_ms_h_tf.log 2>&1
# CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True teacher_forcing_start_value=1.0 teacher_forcing_start_time=2000000 teacher_forcing_end_time=6000000 t_max=100000 exp_name="REFERENCE-QMIX-TRANS-SS-H-TF" >> reference_qmix_trans_ss_h_tf.log 2>&1
# # teacher-student
# CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=100000 exp_name="REFERENCE-QMIX-TRANS-SS-TEACHER" >> reference_qmix_trans_ss_teacher.log 2>&1
# CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_student_start_time=3000000 teacher_student_end_time=7000000 teacher_model_dir="" t_max=100000 exp_name="REFERENCE-QMIX-TRANS-SS-STUDENT" >> reference_qmix_trans_ss_student.log 2>&1
# CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=100000 exp_name="REFERENCE-QMIX-TRANS-SS-H-TEACHER" >> reference_qmix_trans_ss_h_teacher.log 2>&1
# CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_student_start_time=3000000 teacher_student_end_time=7000000 teacher_model_dir="" t_max=100000 exp_name="REFERENCE-QMIX-TRANS-SS-H-STUDENT" >> reference_qmix_trans_ss_h_student.log 2>&1
# CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=100000 exp_name="REFERENCE-QMIX-TRANS-MS-H-TEACHER" >> reference_qmix_trans_ms_h_teacher.log 2>&1
# CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_student_start_time=3000000 teacher_student_end_time=7000000 teacher_model_dir="" t_max=100000 exp_name="REFERENCE-QMIX-TRANS-MS-H-STUDENT" >> reference_qmix_trans_ms_h_student.log 2>&1

# #####gru#####
# CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="multi_step" delay_aware=True t_max=100000 exp_name="REFERENCE-QMIX-GRU-MS" >> reference_qmix_gru_ms.log 2>&1
# CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" delay_aware=True t_max=100000 exp_name="REFERENCE-QMIX-GRU-SS" >> reference_qmix_gru_ss.log 2>&1
# CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="multi_step" delay_aware=True use_history=True t_max=100000 exp_name="REFERENCE-QMIX-GRU-MS-H" >> reference_qmix_gru_ms_h.log 2>&1
# CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" delay_aware=True use_history=True t_max=100000 exp_name="REFERENCE-QMIX-GRU-SS-H" >> reference_qmix_gru_ss_h.log 2>&1
# # curriculum learning
# CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="multi_step" delay_aware=True use_history=True cheating_start_value=1.0 cheating_start_time=2000000 cheating_end_time=6000000 t_max=100000 exp_name="REFERENCE-QMIX-GRU-MS-H-C" >> reference_qmix_gru_ms_h_c.log 2>&1
# CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" delay_aware=True use_history=True cheating_start_value=1.0 cheating_start_time=2000000 cheating_end_time=6000000 t_max=100000 exp_name="REFERENCE-QMIX-GRU-SS-H-C" >> reference_qmix_gru_ss_h_c.log 2>&1
# CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="multi_step" delay_aware=True use_history=True teacher_forcing_start_value=1.0 teacher_forcing_start_time=2000000 teacher_forcing_end_time=6000000 t_max=100000 exp_name="REFERENCE-QMIX-GRU-MS-H-TF" >> reference_qmix_gru_ms_h_tf.log 2>&1
# CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" delay_aware=True use_history=True teacher_forcing_start_value=1.0 teacher_forcing_start_time=2000000 teacher_forcing_end_time=6000000 t_max=100000 exp_name="REFERENCE-QMIX-GRU-SS-H-TF" >> reference_qmix_gru_ss_h_tf.log 2>&1
# # teacher-student
# CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" delay_aware=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=100000 exp_name="REFERENCE-QMIX-GRU-SS-TEACHER" >> reference_qmix_gru_ss_teacher.log 2>&1
# CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" delay_aware=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_student_start_time=3000000 teacher_student_end_time=7000000 teacher_model_dir="" t_max=100000 exp_name="REFERENCE-QMIX-GRU-SS-STUDENT" >> reference_qmix_gru_ss_student.log 2>&1
# CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=100000 exp_name="REFERENCE-QMIX-GRU-SS-H-TEACHER" >> reference_qmix_gru_ss_h_teacher.log 2>&1
# CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_student_start_time=3000000 teacher_student_end_time=7000000 teacher_model_dir="" t_max=100000 exp_name="REFERENCE-QMIX-GRU-SS-H-STUDENT" >> reference_qmix_gru_ss_h_student.log 2>&1
# CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="multi_step" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=100000 exp_name="REFERENCE-QMIX-GRU-MS-H-TEACHER" >> reference_qmix_gru_ms_h_teacher.log 2>&1
# CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="multi_step" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_student_start_time=3000000 teacher_student_end_time=7000000 teacher_model_dir="" t_max=100000 exp_name="REFERENCE-QMIX-GRU-MS-H-STUDENT" >> reference_qmix_gru_ms_h_student.log 2>&1

"""

def clean_command(line):
    line = line.strip()
    # Skip empty lines or comments
    if not line or line.startswith("#"):
        return None
    
    # 1. Remove CUDA_VISIBLE_DEVICES="X"
    line = re.sub(r'CUDA_VISIBLE_DEVICES="\d+"\s+', '', line)
    
    # 2. Remove nohup
    line = re.sub(r'nohup\s+', '', line)
    
    # 3. FORCE 'python' to 'python3'
    # This specifically looks for 'python' as a standalone word
    line = re.sub(r'\bpython\b', 'python3', line)
    
    # 4. Remove output redirection (e.g., >> tag_qmix_b.log 2>&1)
    # We remove this because SLURM handles logging via #SBATCH --output
    line = re.sub(r'\s+>>.*$', '', line)
    
    # 5. Remove trailing ampersand (&)
    line = line.rstrip('&').strip()
    
    return line

# Process the lines
cleaned_list = []
for cmd in raw_commands.split('\n'):
    cleaned = clean_command(cmd)
    if cleaned:
        cleaned_list.append(cleaned)

# Save to experiments.txt
with open("experiments.txt", "w") as f:
    for cmd in cleaned_list:
        f.write(cmd + "\n")

print(f"Success! Generated experiments.txt with {len(cleaned_list)} cleaned python3 commands.")